version: '3.8'

volumes:
  postgres_data: {}
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    expose:
      - "3000"
    volumes:
      - grafana_data:/var/lib/grafana

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - MET_API_USER=${MET_API_USER}
      - MET_API_PASSWORD=${MET_API_PASSWORD}

  postgres:
    image: "postgres:14"
    container_name: postgres
    ports:
      - 5433:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=met-data
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d met-data"]
      interval: 2s
      timeout: 2s
      retries: 5
