{
 "title": "Yr historical data",
 "time": { "from": "2022-10-31T22:49:04.724Z", "to": "2022-11-02T08:11:46.887Z" },
 "templating": {
  "list": [
   { "name": "name", "label": "Location", "query": "SELECT name from sources" },
   {
    "name": "source_id",
    "query": "SELECT source_id from sources where name = '${name}'"
   },
   {
    "name": "element_id",
    "label": "Element",
    "query": "select distinct(element_id) from hourly_data where source_id = '${source_id}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  value,\n  element_id\nFROM\n  hourly_data\nWHERE\n  $__timeFilter(time) AND element_id = 'sum(precipitation_amount PT1H)' AND source_id = '${source_id}' ORDER BY 1"
    }
   ]
  },
  {
   "title": "Surface air pressure (hPa)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM hourly_data\nWHERE\n  $__timeFilter(time) and\n  element_id ='surface_air_pressure'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Visibility in air",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value,\n  element_id\nFROM hourly_data\nWHERE\n  $__timeFilter(time) and\nelement_id ='visibility_in_air_mor' and source_id = '${source_id}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM hourly_data\nWHERE\n  $__timeFilter(time) AND\n  element_id = 'wind_from_direction'AND\n  source_id = '${source_id}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Dew point",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  value,\n  element_id\nFROM\n  hourly_data\nWHERE\n  $__timeFilter(time) AND element_id = 'dew_point_temperature' AND source_id = '${source_id}' ORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM hourly_data\nWHERE\n  $__timeFilter(time) AND\n  element_id = 'air_temperature' AND\n  level = 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Snow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM hourly_data\nWHERE\n  $__timeFilter(time) AND\n  element_id = 'surface_snow_thickness' AND\n  level = 2\nORDER BY 1"
    }
   ]
  }
 ]
}